# =========================================
# API-GATEWAY (prod) - Spring Cloud Config
# 목적: 운영/실서비스용. MSA의 단일 진입점(Single Point of Entry) 역할.
# =========================================
server:
  port: 13000                    # 게이트웨이 HTTP 포트
  shutdown: graceful             # 무중단 배포/롤링 업데이트 시 안전

spring:
  application:
    name: api-gateway       # Config/로그 식별용 서비스명
  config:
    activate:
      on-profile: prod
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]': # 모든 경로(/**)에 대해 아래 CORS 정책 적용
                allowed-origins: "${CORS_ALLOWED_ORIGINS:http://localhost:14000,http://cuecode.kr,https://cuecode.kr,https://api.cuecode.kr}" # Secret이나 환경변수로 주입 권장
                allowed-methods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowed-headers: "*"
                allow-credentials: true
          routes:
            # 1. Motion-Service 라우팅
            - id: motion_service_route
              uri: http://motion-service:15000
              predicates:
                - Path=/motions/**

            # 2. User-Service 라우팅 (API 경로별로 세분화)
            - id: user_login_route
              uri: http://user-service:11000
              predicates:
                - Path=/login/**
            - id: user_users_route
              uri: http://user-service:11000
              predicates:
                - Path=/users/**
            - id: user_manager_route
              uri: http://user-service:11000
              predicates:
                - Path=/manager/**
            - id: user_patient_route
              uri: http://user-service:11000
              predicates:
                - Path=/patient/**
            - id: user_user_info_route
              uri: http://user-service:11000
              predicates:
                - Path=/user/**
            - id: user_reg_route
              uri: http://user-service:11000
              predicates:
                - Path=/reg/**

            # 3. Front-UI 라우팅 규칙 (가장 마지막에 위치해야 함)
            - id: front_ui_route
              uri: http://front-ui-service:14000
              predicates:
                - Path=/**

# Actuator 설정 (최신 방식)
management:
  server:
    port: 13001
    address: 0.0.0.0
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: when_authorized

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO

jwt:
  secret:
    key: ${JWT_SECRET_KEY}

# Service URIs for Kubernetes environment
service:
  uri:
    user: http://user-service:11000
    front: http://front-ui-service:14000
    motion: http://motion-service:15000
