# =========================================
# API-GATEWAY (dev) - 최종 수정본
# =========================================
server:
  port: 13000
  shutdown: graceful

spring:
  application:
    name: api-gateway
  config:
    activate:
      on-profile: dev
  cloud:
    discovery:
      enabled: false
    gateway:
      # --- 모든 요청에 공통으로 시크릿 헤더를 추가 ---
      default-filters:
        - AddRequestHeader=X-Gateway-Secret, cue-code-secret-key-for-internal-communication

      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowed-origins: "http://localhost:14000,http://localhost:3000,http://127.0.0.1:3000"
                allowed-methods: [GET, POST, PUT, DELETE, OPTIONS]
                allowed-headers: "*"
                allow-credentials: true
          routes:
            # 1. Motion-Service 라우팅
            - id: motion_service_route
              uri: ${service.uri.motion}
              predicates:
                - Path=/api/motions/**
              filters:
                - StripPrefix=1

            - id: motion_service_websocket_routeEX
              uri: ws://localhost:15000
              predicates:
                - Path=/ws/motion/**

            - id: motion_service_websocket_route
              uri: ws://localhost:15000
              predicates:
                - Path=/api/ws/motion/**
              filters:
                - StripPrefix=1

            - id: motion_service_websocket_alerts_route
              uri: ws://localhost:15000
              predicates:
                - Path=/api/ws/alerts
              filters:
                - StripPrefix=1

            - id: recorded-motions-v1-route
              uri: ${service.uri.motion}
              predicates:
                - Path=/api/v1/recorded-motions/**

            # 2. User-Service 라우팅
            - id: user_login_route
              uri: ${service.uri.user}
              predicates:
                - Path=/api/login/**
              filters:
                - StripPrefix=1
            - id: user_users_route
              uri: ${service.uri.user}
              predicates:
                - Path=/api/users/**
              filters:
                - StripPrefix=1
            - id: user_manager_route
              uri: ${service.uri.user}
              predicates:
                - Path=/api/manager/**
              filters:
                - StripPrefix=1
            - id: user_patient_route
              uri: ${service.uri.user}
              predicates:
                - Path=/api/patient/**
              filters:
                - StripPrefix=1
            - id: user_user_info_route
              uri: ${service.uri.user}
              predicates:
                - Path=/api/user/**
              filters:
                - StripPrefix=1
            - id: user_reg_route
              uri: ${service.uri.user}
              predicates:
                - Path=/api/reg/**
              filters:
                - StripPrefix=1
            - id: user_find_id_route
              uri: ${service.uri.user}
              predicates:
                - Path=/api/reg/findIdByEmail
              filters:
                - StripPrefix=1
            - id: user-contact
              uri: ${service.uri.user}
              predicates:
                - Path=/api/users/contact/**
              filters:
                - StripPrefix=1

            # 3. Front-UI Service 라우팅 (Specific Routes First)
            - id: front-ui-vendor-assets-route
              uri: ${service.uri.front}
              predicates:
                - Path=/vendor/**

            - id: front-ui-motion-detector-route
              uri: ${service.uri.front}
              predicates:
                - Path=/motion
              filters:
                - RewritePath=/motion, /motion/motion-detector.html

            - id: front-ui-motion-upload-route
              uri: ${service.uri.front}
              predicates:
                - Path=/motion/upload
              filters:
                - RewritePath=/motion/upload, /motion/motion-upload.html

            - id: front-ui-user-dashboard-route
              uri: ${service.uri.front}
              predicates:
                - Path=/user/dashboard
              filters:
                - RewritePath=/user/dashboard, /user/dashboard.html

            # 4. Front-UI Service 라우팅 (General Catch-all)
            - id: front-ui-route
              uri: ${service.uri.front}
              predicates:
                - Path=/, /index.html, /user/**, /css/**, /js/**, /images/**, /motion/**, /patient/**, /manager/**

# (management, logging, jwt, service 설정은 변경 없음)
management:
  server:
    address: localhost
    port: 13001
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.security: TRACE
    reactor.netty.http.client: TRACE

jwt:
  token:
    creator: cuecoder
    access:
      valid:
        time: "600"
      name: jwtAccessToken
    refresh:
      valid:
        time: "7200"
      name: jwtRefreshToken
  secret:
    key: "Ixp3HCXOS5Hi0py81JF610NG5nvySPjBq3VQXPmwsLI="

service:
  uri:
    user: http://localhost:11000
    front: http://localhost:14000
    motion: http://localhost:15000