# =========================================
# API-GATEWAY (dev) - Spring Cloud Config
# 목적: 개발/로컬 테스트용. 로그·Actuator 전면 개방, CORS 완화, 긴 토큰 만료시간.
# =========================================
server:
  port: 13000                    # 게이트웨이 HTTP 포트
  shutdown: graceful             # 요청 처리 후 정상 종료 (개발 편의)

spring:
  application:
    name: api-gateway       # Config/로그 식별용 서비스명
  config:
    activate:
      on-profile: dev            # 이 파일은 dev 프로필에서만 활성화
  cloud:
    discovery:
      enabled: false             # Eureka 등 DiscoveryClient 비활성화
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowed-origins: "http://localhost:14000,http://localhost:3000,http://127.0.0.1:3000"
                allowed-methods: [GET, POST, PUT, DELETE, OPTIONS]
                allowed-headers: "*"
                allow-credentials: true
          routes:
            # 1. Motion-Service 라우팅
            - id: motion_service_route
              uri: ${service.uri.motion}
              predicates:
                - Path=/api/motions/**
              filters:
                - StripPrefix=1

            - id: motion_service_websocket_route
              uri: ws://localhost:15000
              predicates:
                - Path=/ws/motion

            # 2. User-Service 라우팅 (API 경로별로 세분화)
            - id: user_login_route
              uri: ${service.uri.user}
              predicates:
                - Path=/api/login/**
              filters:
                - StripPrefix=1
            - id: user_users_route
              uri: ${service.uri.user}
              predicates:
                - Path=/api/users/**
              filters:
                - StripPrefix=1
            - id: user_manager_route
              uri: ${service.uri.user}
              predicates:
                - Path=/api/manager/**
              filters:
                - StripPrefix=1
            - id: user_patient_route
              uri: ${service.uri.user}
              predicates:
                - Path=/api/patient/**
              filters:
                - StripPrefix=1
            - id: user_user_info_route
              uri: ${service.uri.user}
              predicates:
                - Path=/api/user/**
              filters:
                - StripPrefix=1
            - id: user_reg_route
              uri: ${service.uri.user}
              predicates:
                - Path=/api/reg/**
              filters:
                - StripPrefix=1

            - id: user-contact
              uri: ${service.uri.user}
              predicates:
                - Path=/api/users/contact
              filters:
                - StripPrefix=1 # '/api' 접두사 제거

# Actuator 설정 (최신 방식)
management:
  server:
    address: localhost           # Actuator를 로컬에서만 노출 (개발)
    port: 13001                  # Actuator 포트(서버와 분리)
  endpoints:
    web:
      exposure:
        include: "*"             # 개발은 전부 노출(beans, env 등) — 운영에선 금지!
  endpoint:
    health:
      show-details: always       # 상세 헬스 정보 표시 (개발 디버깅용)

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.security: TRACE # Security 상세 로그 활성화
    reactor.netty.http.client: TRACE # Netty 클라이언트 상세 로그 활성화

# JWT (개발용) — 게이트웨이와 토큰 발급/검증 서비스가 '동일한 키'를 사용해야 함
jwt:
  token:
    creator: cuecoder            # iss 등 메타로 활용 가능
    access:
      valid:
        time: "600"              # Access Token 유효시간(초) — 10분
      name: jwtAccessToken
    refresh:
      valid:
        time: "7200"             # Refresh Token 유효시간(초) — 2시간
      name: jwtRefreshToken
  secret:
    key: "Ixp3HCXOS5Hi0py81JF610NG5nvySPjBq3VQXPmwsLI="

# Service URIs for local development
service:
  uri:
    user: http://localhost:11000
    front: http://localhost:14000
    motion: http://localhost:15000