# =========================================
# API-GATEWAY (prod) - Spring Cloud Config
# 목적: 운영/실서비스용. MSA의 단일 진입점(Single Point of Entry) 역할.
# =========================================
server:
  port: 13000                    # 게이트웨이 HTTP 포트
  shutdown: graceful             # 무중단 배포/롤링 업데이트 시 안전

spring:
  application:
    name: api-gateway            # [수정] 일관성을 위해 소문자-하이픈 사용
  config:
    # [수정] 다른 spring 블록과 통합
    import: "optional:configserver:http://config-server-service:8888/"
  cloud:
    gateway:
      # ===============================================
      # ▼▼▼▼▼▼▼▼▼▼ 라우팅 및 CORS 설정 수정 ▼▼▼▼▼▼▼▼▼▼
      # ===============================================
      routes:
        # 1. User-Service 라우팅 규칙
        - id: user_service_route
          # [수정] K8s 서비스 디스커버리를 위한 lb(Load Balancer) 프로토콜 사용
          uri: lb://user-service
          predicates:
            - Path=/user-service/** # /user-service/로 시작하는 모든 경로
          filters:
            # /user-service/api -> /api 처럼 앞 경로를 제거해주는 필터
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

        # 2. Motion-Service 라우팅 규칙
        - id: motion_service_route
          uri: lb://motion-service
          predicates:
            - Path=/motion-service/**
          filters:
            - RewritePath=/motion-service/(?<segment>.*), /$\{segment}

        # 3. Front-UI 라우팅 규칙 (가장 마지막에 위치해야 함)
        # 위에서 처리되지 않은 나머지 모든 요청을 프론트엔드로 전달
        - id: front_ui_route
          uri: lb://front-ui-service # ★ front-ui를 노출하는 서비스 이름
          predicates:
            - Path=/**

      # [수정] Spring Cloud Gateway의 공식적인 CORS 설정 방식
      globalcors:
        cors-configurations:
          '[/**]': # 모든 경로(/**)에 대해 아래 CORS 정책 적용
            allowed-origins: "${CORS_ALLOWED_ORIGINS:http://localhost:14000}" # Secret이나 환경변수로 주입 권장
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-headers: "*"
            allow-credentials: true

# ... management, logging, jwt 등 나머지 설정은 이전과 동일 ...
management:
  server:
    port: 13001
    address: 0.0.0.0
  endpoints:
    web:
      exposure:
        include: [health, info, prometheus]

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO

jwt:
  secret:
    key: ${JWT_SECRET}