server:
  port: 15000

spring:
  application:
    name: motion-service
  data:
    mongodb:
      uri: mongodb://poly:poly1234@localhost:27017/motionDB?authSource=motionDB
      auto-index-creation: true
      uuid-representation: standard

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true