# =========================================
# Motion-Service (prod) - Spring Cloud Config
# 목적: 운영 환경용. 민감 정보는 K8s Secret으로 주입, 성능 최적화 설정.
# =========================================
server:
  port: 15000
  shutdown: graceful

# spring: 키 아래에 모든 스프링 관련 설정을 배치합니다.
spring:
  application:
    name: motion-service
  config:
    activate:
      on-profile: prod
  # data: 키를 spring: 아래로 이동시키고 올바르게 들여쓰기합니다.
  data:
    mongodb:
      host: ${MONGO_HOST}
      port: ${MONGO_PORT}
      database: ${MONGO_DB}
      username: ${MONGO_USER}
      password: ${MONGO_PASSWORD}
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT} # K8s Secret에서 값을 가져오도록 수정
      password: ${REDIS_PASSWORD}

# 외부 서비스 URL (독립적인 설정)
cuecodemotion:
  url: http://cuecode-motion-service:8000

# 운영 환경 로깅 설정
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    kopo.motionservice: INFO

# Actuator 보안 설정
management:
  server:
    port: 15001
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: when-authorized

# JWT 설정을 독립적인 최상위 키로 분리합니다.
jwt:
  token:
    creator: cuecoder
    access:
      valid:
        time: "300"
      name: jwtAccessToken
    refresh:
      valid:
        time: "3600"
      name: jwtRefreshToken
    cookie:
      domain: .cuecode.kr
  secret:
    key: ${JWT_SECRET}

gateway:
  trusted:
    secret: ${GATEWAY_TRUSTED_SECRET:cue-code-secret-key-for-internal-communication}