# =========================================
# Motion-Service (prod) - Spring Cloud Config
# 목적: 운영 환경용. 민감 정보는 K8s Secret으로 주입, 성능 최적화 설정.
# =========================================
server:
  port: 15000
  shutdown: graceful # 운영 환경에서는 요청을 모두 처리하고 안전하게 종료하는 것이 중요합니다.

spring:
  application:
    name: motion-service
  config:
    activate:
      on-profile: prod # 이 파일은 prod 프로필에서만 활성화됩니다.
  data:
    # --- [수정됨] mongodb와 redis가 data 하위에 있도록 들여쓰기 수정 ---
    mongodb:
      host: ${MONGO_HOST}
      port: ${MONGO_PORT}
      database: ${MONGO_DB}
      username: ${MONGO_USER}
      password: ${MONGO_PASSWORD}
    redis:
      host: ${REDIS_HOST}
      port: 6379
      password: ${REDIS_PASSWORD}

# 운영 환경 로깅 설정
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    kopo.motionservice: INFO

# Actuator 보안 설정: 운영에서는 최소한의 엔드포인트만 노출합니다.
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus # 헬스체크, 기본정보, 모니터링 메트릭만 노출
  endpoint:
    health:
      show-details: when-authorized # 인증된 호출에 한해 상세 정보 제공